<Project>
  <ItemGroup>
    <ProjectReference Include="$(MSBuildThisFileDirectory)Engine.Shared\Engine.Shared.csproj" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)Engine.Generators\Engine.Generators.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
